name: 'Setup Lazarus environment'

description: 'Setup a Lazarus environment adding it to the PATH'

branding:
  icon: 'chevrons-right'
  color: 'blue'

inputs:
  lazarus-version:  # id of input
    description: 'Version of Lazarus'
    required: true
    default: 'dist'
  include-packages-opm:
    description: 'Include OPM packages that the project needs'
    required: false
  include-packages-local:
    description: 'Include local packages that the project needs'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'

